# Pair与字典

In [4]:
p = :China => :Asia
typeof(p)

Pair{Symbol, Symbol}

In [5]:
Dict(p)

Dict{Symbol, Symbol} with 1 entry:
  :China => :Asia

# 元组与命名元组

In [8]:
t1, t2 = tuple(1, 2, 3), (1, 2, 4)
typeof(t2)

Tuple{Int64, Int64, Int64}

In [13]:
nt = (China = :Asia, US = :NA)
typeof(nt)

@NamedTuple{China::Symbol, US::Symbol}

# 多维数组 

`Array{T, N} <: DenseArray{T, N} <:AbstractArray{T, N}`

`T`为元素类型，`N`为数组的维度

创建数组`Array{T, N}(undef, dims)`, 其中`dims`的维度等于N

In [1]:
Array{Int64, 3}(undef, (2, 2, 3))

2×2×3 Array{Int64, 3}:
[:, :, 1] =
  1  3
 -1  4

[:, :, 2] =
  5  7
 -1  8

[:, :, 3] =
  9  11
 10  -1

In [1]:
# 通用的数组构造方法
Array{Int64, 3}(undef, (2, 2, 3))

2×2×3 Array{Int64, 3}:
[:, :, 1] =
 140718380945648  140718380945648
 140718380945648  140718380945648

[:, :, 2] =
 140718380945648  140718380945648
 140718380945648  140718380945648

[:, :, 3] =
 140718380945648  140718380945648
 140718380945648  140718380945648

两种特殊的数组`Vector`, `Matrix`, 仅仅是`array`的别名`alias`

In [2]:
Vector

Vector (alias for Array{T, 1} where T)

In [3]:
Matrix

Matrix (alias for Array{T, 2} where T)

In [4]:
Vector{Float64}(undef, 4)

4-element Vector{Float64}:
 1.38191521e-315
 1.207689203e-314
 1.38084012e-315
 9.3238788e-316

In [5]:
Matrix{Float64}(undef, (4, 4))

4×4 Matrix{Float64}:
 0.0           1.3612e-315   1.36106e-315  0.0
 1.3612e-315   1.36106e-315  0.0           1.3612e-315
 1.36106e-315  0.0           1.3612e-315   1.57072e-315
 0.0           1.3612e-315   1.38654e-315  0.0

In [6]:
[1, 2, 3, 4.0]

4-element Vector{Float64}:
 1.0
 2.0
 3.0
 4.0

In [7]:
[1; 2; 3; 4.0]

4-element Vector{Float64}:
 1.0
 2.0
 3.0
 4.0

In [8]:
# matrix
[1 2 3 4]

1×4 Matrix{Int64}:
 1  2  3  4

In [9]:
[1 2;
 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

只有列向量时一维数组，行向量是一个二维数组或矩阵

+ 创建向量时请使用`,`，他就会自动生成一个列向量
+ 创建矩阵时，尽量使用`;`区分不同行，使用`space`区分不同列，`,`不能区分什么，应尽量减少使用

In [10]:
Float64[1.0 2;
        3 4]

2×2 Matrix{Float64}:
 1.0  2.0
 3.0  4.0

In [11]:
Int64[1, 2, 3, 4, 5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [12]:
zero_m = zeros(Float64, (3, 4))

3×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [13]:
one_m = ones(Float64, (1, 4))

1×4 Matrix{Float64}:
 1.0  1.0  1.0  1.0

In [14]:
zero_one = vcat(zero_m, one_m)

4×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 1.0  1.0  1.0  1.0

In [119]:
diag1 = Array{Float64, 2}(UniformScaling(pi), (4, 4))

4×4 Matrix{Float64}:
 3.14159  0.0      0.0      0.0
 0.0      3.14159  0.0      0.0
 0.0      0.0      3.14159  0.0
 0.0      0.0      0.0      3.14159

In [120]:
mat = hcat(zero_one, diag1)

4×8 Matrix{Float64}:
 0.0  0.0  0.0  0.0  3.14159  0.0      0.0      0.0
 0.0  0.0  0.0  0.0  0.0      3.14159  0.0      0.0
 0.0  0.0  0.0  0.0  0.0      0.0      3.14159  0.0
 1.0  1.0  1.0  1.0  0.0      0.0      0.0      3.14159

In [121]:
size(mat, 1)

4

In [122]:
size(mat)

(4, 8)

In [123]:
length(mat)

32

In [124]:
eltype(mat)

Float64

In [125]:
ndims(mat)

2

## 范围表达式

In [126]:
collect(1:2:9)

5-element Vector{Int64}:
 1
 3
 5
 7
 9

In [127]:
range(1, 9; step = 1)

1:1:9

In [128]:
for i in range(1, 9; step = 1)
    if i % 2 == 0
        println("$i % 2 == 0")
    end
end

2 % 2 == 0
4 % 2 == 0
6 % 2 == 0
8 % 2 == 0


## 推导式

In [129]:
[i * j for i in 1:3, j = 3:4]

3×2 Matrix{Int64}:
 3   4
 6   8
 9  12

In [130]:
m1 = Float64[i * j for i in 1:3, j in 1:4]

3×4 Matrix{Float64}:
 1.0  2.0  3.0   4.0
 2.0  4.0  6.0   8.0
 3.0  6.0  9.0  12.0

## 笛卡尔索引（Cartesian Indexing)

In [131]:
m1[1, 2]

2.0

In [132]:
m1[3, end]

12.0

In [133]:
m1[2:end, 2:(end - 1)]

2×2 Matrix{Float64}:
 4.0  6.0
 6.0  9.0

In [134]:
# 也是一个向量
m1[2, 2:3]

2-element Vector{Float64}:
 4.0
 6.0

In [135]:
# 按照行或者按照列取出来都是一个向量
m1[1,:]

4-element Vector{Float64}:
 1.0
 2.0
 3.0
 4.0

In [136]:
m1[:, 1]

3-element Vector{Float64}:
 1.0
 2.0
 3.0

In [137]:
m1

3×4 Matrix{Float64}:
 1.0  2.0  3.0   4.0
 2.0  4.0  6.0   8.0
 3.0  6.0  9.0  12.0

## reshape

In [138]:
vec(m1)

12-element Vector{Float64}:
  1.0
  2.0
  3.0
  2.0
  4.0
  6.0
  3.0
  6.0
  9.0
  4.0
  8.0
 12.0

In [146]:
m1[:]

12-element Vector{Float64}:
 1000.0
    2.0
    3.0
    2.0
    4.0
    6.0
    3.0
    6.0
    9.0
    4.0
    8.0
   12.0

In [147]:
reshape(m1, 12)

12-element Vector{Float64}:
 1000.0
    2.0
    3.0
    2.0
    4.0
    6.0
    3.0
    6.0
    9.0
    4.0
    8.0
   12.0

In [148]:
reshape(m1, 12, 1)

12×1 Matrix{Float64}:
 1000.0
    2.0
    3.0
    2.0
    4.0
    6.0
    3.0
    6.0
    9.0
    4.0
    8.0
   12.0

In [149]:
m1

3×4 Matrix{Float64}:
 1000.0  2.0  3.0   4.0
    2.0  4.0  6.0   8.0
    3.0  6.0  9.0  12.0

`reshape`是对原有数组的引用，`reshape`后的数组的修改会反应到原数组中

In [150]:
v2 = reshape(m1, 12)

12-element Vector{Float64}:
 1000.0
    2.0
    3.0
    2.0
    4.0
    6.0
    3.0
    6.0
    9.0
    4.0
    8.0
   12.0

In [151]:
v2[1] = 1000

1000

In [152]:
v2

12-element Vector{Float64}:
 1000.0
    2.0
    3.0
    2.0
    4.0
    6.0
    3.0
    6.0
    9.0
    4.0
    8.0
   12.0

In [153]:
m1

3×4 Matrix{Float64}:
 1000.0  2.0  3.0   4.0
    2.0  4.0  6.0   8.0
    3.0  6.0  9.0  12.0

## reduce

In [154]:
map(x -> x^2, 1:3)

3-element Vector{Int64}:
 1
 4
 9

In [155]:
reduce(+, 1:3)

6

In [156]:
# 先map然后再reduce
mapreduce(x->x^2, +, 1:3)

14

In [157]:
a = randn(2, 2)

2×2 Matrix{Float64}:
 -1.66396  -0.745054
  1.30388   1.13061

In [158]:
permutedims(a, (2, 1))

2×2 Matrix{Float64}:
 -1.66396   1.30388
 -0.745054  1.13061

## 视图

In [159]:
m1[1, 1] = 1

1

In [160]:
m1

3×4 Matrix{Float64}:
 1.0  2.0  3.0   4.0
 2.0  4.0  6.0   8.0
 3.0  6.0  9.0  12.0

In [161]:
m1[1, :] = [4, 3, 2, 1]

4-element Vector{Int64}:
 4
 3
 2
 1

In [162]:
m1

3×4 Matrix{Float64}:
 4.0  3.0  2.0   1.0
 2.0  4.0  6.0   8.0
 3.0  6.0  9.0  12.0

视图与正常的索引有什么区别？
+ 如果需要直接修改原来的数组好像也没啥区别，貌似view快一点
+ 如果是先取出数组的某一块然后赋值给一个新变量，这时view的数组上的修改会直接反应到原来的数组上，但是新变量的修改并不会反映到原来数组上，因为新变量是取出的数组块的复制。

> 当涉及到的矩阵比较大时用view,只涉及索引不涉及赋值用view

In [163]:
B = m1[2, :]

4-element Vector{Float64}:
 2.0
 4.0
 6.0
 8.0

In [164]:
B[1] = 100

100

In [165]:
m1

3×4 Matrix{Float64}:
 4.0  3.0  2.0   1.0
 2.0  4.0  6.0   8.0
 3.0  6.0  9.0  12.0

In [166]:
B

4-element Vector{Float64}:
 100.0
   4.0
   6.0
   8.0

In [167]:
C = @view m1[2, :]

4-element view(::Matrix{Float64}, 2, :) with eltype Float64:
 2.0
 4.0
 6.0
 8.0

In [168]:
C[1] = 100

100

In [169]:
m1

3×4 Matrix{Float64}:
   4.0  3.0  2.0   1.0
 100.0  4.0  6.0   8.0
   3.0  6.0  9.0  12.0

In [170]:
rmat = rand(10000, 10000);

In [171]:
using BenchmarkTools

In [172]:
@benchmark @view rmat[3:5000, 1299:2:3000]

BenchmarkTools.Trial: 10000 samples with 993 evaluations.
 Range (min … max):  33.938 ns …  39.996 μs  ┊ GC (min … max): 0.00% … 99.81%
 Time  (median):     53.273 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   55.977 ns ± 399.541 ns  ┊ GC (mean ± σ):  7.13% ±  1.00%

  ▅▂▅▅▂ ▁ ▁▁                ▄▆██▅▃▂▃▄▄▄▄▃▂▂▂▂▂▁▁▁▁▁            ▂
  ███████████▇▇▄▅▄▂▄▃▃▂▂▃▃▂▅██████████████████████████▇██▇▇▇▇▆ █
  33.9 ns       Histogram: log(frequency) by time      73.9 ns <

 Memory estimate: 80 bytes, allocs estimate: 1.

In [173]:
@benchmark rmat[3:5000, 1299:2:3000]

BenchmarkTools.Trial: 513 samples with 1 evaluation.
 Range (min … max):  7.287 ms … 38.959 ms  ┊ GC (min … max):  0.00% … 74.06%
 Time  (median):     7.848 ms              ┊ GC (median):     0.00%
 Time  (mean ± σ):   9.739 ms ±  5.956 ms  ┊ GC (mean ± σ):  16.00% ± 18.44%

  █▇▃▄▂▂                                                      
  ██████▇▁▅▄▁▁▁▁▁▁▁▁▁▁▁▁▁▁▄▁▁▁▁▁▁▁▄▁▁▁▁▁▁▄▇▇▅▁▄▄▄▄▁▁▁▄▄▁▄▁▅▇ ▇
  7.29 ms      Histogram: log(frequency) by time     35.3 ms <

 Memory estimate: 32.45 MiB, allocs estimate: 2.

## 矢量化计算

In [174]:
a = [1.2, 3.5, -2.1]

3-element Vector{Float64}:
  1.2
  3.5
 -2.1

In [175]:
map((x) -> x + 1, a)

3-element Vector{Float64}:
  2.2
  4.5
 -1.1

In [176]:
map(a) do element
    element + 1
end

3-element Vector{Float64}:
  2.2
  4.5
 -1.1

In [177]:
map(a) do element
        if element < 0
            return 0
        elseif element > 0 && element < 3
            return Int64(round(element))
        else
            return 1000
        end
end
        

3-element Vector{Int64}:
    1
 1000
    0

In [178]:
broadcast(+, (1, 2, 3), -1)

(0, 1, 2)

In [179]:
c = (2, 3, -5, 5)

(2, 3, -5, 5)

In [180]:
b = (0, 1, -1, -2)

(0, 1, -1, -2)

In [181]:
max.(c, b)

(2, 3, -1, 5)

In [182]:
max(c, b)

(2, 3, -5, 5)

In [183]:
@. max(c, b)

(2, 3, -1, 5)

In [184]:
@__dot__ max(c, b)

(2, 3, -1, 5)

## 排序

In [185]:
a = [2, 3, 1, 4]

4-element Vector{Int64}:
 2
 3
 1
 4

In [186]:
sort(a)

4-element Vector{Int64}:
 1
 2
 3
 4

In [187]:
sortperm(a) # 获得排序前个元素的下标值

4-element Vector{Int64}:
 3
 1
 2
 4

In [188]:
b = [1  2  3;
     4  1  2;
     0  3  7]

3×3 Matrix{Int64}:
 1  2  3
 4  1  2
 0  3  7

In [189]:
sort(b, dims = 1)

3×3 Matrix{Int64}:
 0  1  2
 1  2  3
 4  3  7

In [190]:
sort(b, dims = 2)

3×3 Matrix{Int64}:
 1  2  3
 1  2  4
 0  3  7

In [191]:
sort(b, dims = 2, rev = true)

3×3 Matrix{Int64}:
 3  2  1
 4  2  1
 7  3  0

## 查找

In [192]:
1 in [1, 2, 3]

true

In [193]:
in(1, [1, 2, 3])

true

In [194]:
findmax([3, -1, 1, 2, 4])

(4, 5)

In [195]:
a = [1  4  -1;
     3  2   0;
     2  5   1]

3×3 Matrix{Int64}:
 1  4  -1
 3  2   0
 2  5   1

In [196]:
findmax(a, dims =1)[2][1]

CartesianIndex(2, 1)

In [197]:
a[findmax(a, dims =1)[2][1]]

3

In [198]:
findall(iszero, a)

1-element Vector{CartesianIndex{2}}:
 CartesianIndex(2, 3)

In [199]:
findall(isone, a)

2-element Vector{CartesianIndex{2}}:
 CartesianIndex(1, 1)
 CartesianIndex(3, 3)

## 矩阵操作

### 常用矩阵操作

In [200]:
using LinearAlgebra

In [201]:
A = rand(3, 3)

3×3 Matrix{Float64}:
 0.736392  0.485306  0.327639
 0.313533  0.195399  0.501836
 0.217461  0.328178  0.124285

In [202]:
tr(A)

1.056076821120192

In [203]:
det(A)

-0.04955353369607077

In [204]:
inv(A)

3×3 Matrix{Float64}:
  2.83342  -0.952653  -3.62282
 -1.41588  -0.409138   5.38452
 -1.21894   2.74718    0.166871

In [205]:
A'

3×3 adjoint(::Matrix{Float64}) with eltype Float64:
 0.736392  0.313533  0.217461
 0.485306  0.195399  0.328178
 0.327639  0.501836  0.124285

In [206]:
eigvals(A)

3-element Vector{Float64}:
 -0.25004078943658975
  0.17524712347980237
  1.1308704870769786

In [207]:
eigvecs(A)

3×3 Matrix{Float64}:
  0.196809   0.721065  0.829228
 -0.791066  -0.544363  0.453311
  0.579207  -0.428642  0.326939

In [208]:
diag_mat = Diagonal([1, 2, 3])

3×3 Diagonal{Int64, Vector{Int64}}:
 1  ⋅  ⋅
 ⋅  2  ⋅
 ⋅  ⋅  3

### 科列斯基矩阵分解

(1)   

给定一个**半正定的对称矩阵 A**, 可以分解成**A = R'R**， R是一个上三角矩阵， 这样做的用处是， 直接对A求逆复杂度很高， 但是对于一个上三角矩阵或下三角矩阵却很简单

In [209]:
using LinearAlgebra

In [210]:
A = [1 0 1; 0 2 0; 1 0 3]

3×3 Matrix{Int64}:
 1  0  1
 0  2  0
 1  0  3

In [211]:
R = cholesky(A).U

3×3 UpperTriangular{Float64, Matrix{Float64}}:
 1.0  0.0      1.0
  ⋅   1.41421  0.0
  ⋅    ⋅       1.41421

In [212]:
b = sum(A; dims = 2)

3×1 Matrix{Int64}:
 2
 2
 4

In [213]:
# Ax = b, x = inv(A) b = inv(R) inv(R') b
inv(R) * inv(R') * b

3×1 Matrix{Float64}:
 1.0000000000000002
 0.9999999999999998
 0.9999999999999998

In [214]:
using Test
@test isapprox(inv(R) * inv(R') * b, inv(A) * b)

Test Passed

(2)

此外， 他也近似于对一个矩阵开根号， 例如协方差对角矩阵开根号则对角线元素为标准差

In [215]:
A = diagm([1, 4, 9])

3×3 Matrix{Int64}:
 1  0  0
 0  4  0
 0  0  9

In [216]:
cholesky(A).U

3×3 UpperTriangular{Float64, Matrix{Float64}}:
 1.0  0.0  0.0
  ⋅   2.0  0.0
  ⋅    ⋅   3.0

# 数据结构的保存

可以使用`JLD2.jl`来写入和读取文件。   
*注意* 
+ Julia自带的数据类型，例如`Vector{Matrix}`这种支持的很好，但是像是Optim优化得到的对象，也支持，不过注意在`JLD2.@load`之前要导入该数据类型需要的包，例如`Optim, ForwardDiff, LineSearches`。
+ Julia没法像R、Matlab一样保存整个工作空间，但是我们可以首选选择多个变量保存到一个文件中去

In [1]:
using JLD2 
x = [[1, 2], [1, 2]]
y = randn(10, 10)
z = "hello"
d = [rand(10), rand(3, 3)]

JLD2.@save "./Data/test.jld2" x y z d
JLD2.@load "./Data/test.jld2" x y z d

4-element Vector{Symbol}:
 :x
 :y
 :z
 :d

# 浅拷贝与深拷贝

reference:
+ https://discourse.julialang.org/t/what-is-the-difference-between-copy-and-deepcopy/3918/3?u=strange_xue

## `b = a`

shallow copy and deep copy

immutable的数据copy-by-value， `b = a`会复制`a`所指向的value

In [15]:
a = 100
b = a
a = 1
b

100

mutable数据copy-by-reference, `b = a`实际上是两个地址指向同一块数据

In [37]:
using StaticArrays
a = SVector(1, 2, 3, 4, 5)
b = a
a = SVector(1, 2)
b

5-element SVector{5, Int64} with indices SOneTo(5):
 1
 2
 3
 4
 5

## `b = copy(a)`

`b = copy(a)`为浅拷贝(shallow copy)： 首先创建一个与a及a的元素相同的容器b， 然后遍历a与b的每一个位置，如果a中的元素为immutable那就copy-by-value， mutable就copy-by-reference

In [54]:
a = [[1, 1, 2], 1, 2]
b = copy(a)
a[1][1] = 10000
a[2] = 10000
b

3-element Vector{Any}:
  [10000, 1, 2]
 1
 2

### `b = deepcopy(a)`

深拷贝， a与b相互独立

In [67]:
a = [[1, 1, 2], 1, 2]
b = deepcopy(a)
a[1][1] = 10000
a[2] = 10000
b

3-element Vector{Any}:
  [1, 1, 2]
 1
 2

# Memory Stack and Heap

https://discourse.julialang.org/t/a-nice-explanation-of-memory-stack-vs-heap/53915?u=strange_xue

Julia `@btime`输出的allocation表示在heap上占用的空间（不包含在stack上占用的）

为什么存在heap上慢： 向操作系统申请内存， 寻找到一块大小合适的区域， 存下， 记录下这个位置被占了方便后来的内存申请

StaticArrays单独使用时存在Stack上

In [30]:
using BenchmarkTools
using StaticArrays

function m1()
    a = SVector(1:4...)
    b = [a] # copy by value
    a = SVector(1:5...)
    return b
end
@btime m1() # 0 allocations

  28.414 ns (1 allocation: 96 bytes)


1-element Vector{SVector{4, Int64}}:
 [1, 2, 3, 4]

In [72]:
function m2()
    a = [1, 2, 3, 4]
    b = [a, 1] # copy by reference
    a[1] = 100
    b[1][2] = 200000 # a also changed
    return b, a
end
@btime m2()  

  100.532 ns (4 allocations: 224 bytes)


(Any[[100, 200000, 3, 4], 1], [100, 200000, 3, 4])

In [74]:
struct Mem{T <: Real}
    x::T
    y::T
end
function m3()
    a = Mem(1.0, 1.0)
    b = Mem(1, 1)
    return a, b
end
@btime m3() # 0 allocations, a, b is stored in stack

  1.200 ns (0 allocations: 0 bytes)


(Mem{Float64}(1.0000, 1.0000), Mem{Int64}(1, 1))

In [76]:
function m4()
    a = Mem(1.0, 1.0)
    b = Mem(1, 1)
    c = [a, b] # copy by value, as a and b are immutable objects
    c[1] = Mem(1000, 1) # a holds same
    return c, a
end
@btime m4()

  25.427 ns (1 allocation: 64 bytes)


(Mem[Mem{Int64}(1000, 1), Mem{Int64}(1, 1)], Mem{Float64}(1.0000, 1.0000))

⏰现在来理解一下`Array{struct}`，即在一个数组（mutable struct）中，每一个元素是不可变对象（immutable struct）从拷贝的角度来讲， 该数组将会在heap上创建，同时每一个元素都是stack上不可变元素的copy（或者说压根就没有拷贝，而是直接创建在了heap上）