# 多维数组 

`Array{T, N} <: DenseArray{T, N} <:AbstractArray{T, N}`

`T`为元素类型，`N`为数组的维度

创建数组`Array{T, N}(undef, dims)`, 其中`dims`的维度等于N

In [20]:
# 通用的数组构造方法
Array{Int64, 3}(undef, (2, 2, 3))

2×2×3 Array{Int64, 3}:
[:, :, 1] =
 3   7
 5  17

[:, :, 2] =
 23  25
 24  28

[:, :, 3] =
 30  35
 34  36

两种特殊的数组`Vector`, `Matrix`, 仅仅是`array`的别名`alias`

In [23]:
Vector

Vector{T} where T (alias for Array{T, 1} where T)

In [24]:
Matrix

Matrix{T} where T (alias for Array{T, 2} where T)

In [25]:
Vector{Float64}(undef, 4)

4-element Vector{Float64}:
 2.0e-323
 1.0e-323
 1.568272106e-315
 1.35368398e-315

In [26]:
Matrix{Float64}(undef, (4, 4))

4×4 Matrix{Float64}:
 9.01035e-315  8.90594e-315  8.9025e-315  8.89659e-315
 8.91041e-315  8.92245e-315  8.9025e-315  8.89659e-315
 8.98886e-315  8.9025e-315   8.9025e-315  8.90538e-315
 8.97257e-315  8.9025e-315   8.9025e-315  8.90538e-315

In [27]:
[1, 2, 3, 4.0]

4-element Vector{Float64}:
 1.0
 2.0
 3.0
 4.0

In [28]:
[1; 2; 3; 4.0]

4-element Vector{Float64}:
 1.0
 2.0
 3.0
 4.0

In [30]:
# matrix
[1 2 3 4]

1×4 Matrix{Int64}:
 1  2  3  4

In [32]:
[1 2;
 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

只有列向量时一维数组，行向量是一个二维数组或矩阵

+ 创建向量时请使用`,`，他就会自动生成一个列向量
+ 创建矩阵时，尽量使用`;`区分不同行，使用`space`区分不同列，`,`不能区分什么，应尽量减少使用

In [35]:
Float64[1.0 2;
        3 4]

2×2 Matrix{Float64}:
 1.0  2.0
 3.0  4.0

In [37]:
Int64[1, 2, 3, 4, 5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [39]:
zero_m = zeros(Float64, (3, 4))

3×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [40]:
one_m = ones(Float64, (1, 4))

1×4 Matrix{Float64}:
 1.0  1.0  1.0  1.0

In [47]:
zero_one = vcat(zero_m, one_m)

4×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 1.0  1.0  1.0  1.0

In [50]:
diag1 = Array(UniformScaling{Float64}(pi), (4, 4))

4×4 Matrix{Float64}:
 3.14159  0.0      0.0      0.0
 0.0      3.14159  0.0      0.0
 0.0      0.0      3.14159  0.0
 0.0      0.0      0.0      3.14159

In [52]:
mat = hcat(zero_one, diag1)

4×8 Matrix{Float64}:
 0.0  0.0  0.0  0.0  3.14159  0.0      0.0      0.0
 0.0  0.0  0.0  0.0  0.0      3.14159  0.0      0.0
 0.0  0.0  0.0  0.0  0.0      0.0      3.14159  0.0
 1.0  1.0  1.0  1.0  0.0      0.0      0.0      3.14159

In [54]:
size(mat, 1)

4

In [55]:
size(mat)

(4, 8)

In [56]:
length(mat)

32

In [57]:
eltype(mat)

Float64

In [58]:
ndims(mat)

2

## 范围表达式

In [61]:
collect(1:2:9)

5-element Vector{Int64}:
 1
 3
 5
 7
 9

In [65]:
range(1, 9; step = 1)

1:1:9

In [66]:
for i in range(1, 9; step = 1)
    if i % 2 == 0
        println("$i % 2 == 0")
    end
end

2 % 2 == 0
4 % 2 == 0
6 % 2 == 0
8 % 2 == 0


## 推导式

In [67]:
[i * j for i in 1:3, j = 3:4]

3×2 Matrix{Int64}:
 3   4
 6   8
 9  12

In [71]:
m1 = Float64[i * j for i in 1:3, j in 1:4]

3×4 Matrix{Float64}:
 1.0  2.0  3.0   4.0
 2.0  4.0  6.0   8.0
 3.0  6.0  9.0  12.0

## 笛卡尔索引（Cartesian Indexing)

In [72]:
m1[1, 2]

2.0

In [79]:
m1[3, end]

12.0

In [80]:
m1[2:end, 2:(end - 1)]

2×2 Matrix{Float64}:
 4.0  6.0
 6.0  9.0

In [82]:
# 也是一个向量
m1[2, 2:3]

2-element Vector{Float64}:
 4.0
 6.0

In [76]:
# 按照行或者按照列取出来都是一个向量
m1[1,:]

4-element Vector{Float64}:
 1.0
 2.0
 3.0
 4.0

In [75]:
m1[:, 1]

3-element Vector{Float64}:
 1.0
 2.0
 3.0

In [83]:
m1

3×4 Matrix{Float64}:
 1.0  2.0  3.0   4.0
 2.0  4.0  6.0   8.0
 3.0  6.0  9.0  12.0

## reshape

In [84]:
vec(m1)

12-element Vector{Float64}:
  1.0
  2.0
  3.0
  2.0
  4.0
  6.0
  3.0
  6.0
  9.0
  4.0
  8.0
 12.0

In [85]:
m1[:]

12-element Vector{Float64}:
  1.0
  2.0
  3.0
  2.0
  4.0
  6.0
  3.0
  6.0
  9.0
  4.0
  8.0
 12.0

In [89]:
reshape(m1, 12)

12-element Vector{Float64}:
  1.0
  2.0
  3.0
  2.0
  4.0
  6.0
  3.0
  6.0
  9.0
  4.0
  8.0
 12.0

In [90]:
reshape(m1, 12, 1)

12×1 Matrix{Float64}:
  1.0
  2.0
  3.0
  2.0
  4.0
  6.0
  3.0
  6.0
  9.0
  4.0
  8.0
 12.0

In [91]:
m1

3×4 Matrix{Float64}:
 1.0  2.0  3.0   4.0
 2.0  4.0  6.0   8.0
 3.0  6.0  9.0  12.0

`reshape`是对原有数组的引用，`reshape`后的数组的修改会反应到原数组中

In [94]:
v2 = reshape(m1, 12)

12-element Vector{Float64}:
  1.0
  2.0
  3.0
  2.0
  4.0
  6.0
  3.0
  6.0
  9.0
  4.0
  8.0
 12.0

In [95]:
v2[1] = 1000

1000

In [96]:
v2

12-element Vector{Float64}:
 1000.0
    2.0
    3.0
    2.0
    4.0
    6.0
    3.0
    6.0
    9.0
    4.0
    8.0
   12.0

In [98]:
m1

3×4 Matrix{Float64}:
 1000.0  2.0  3.0   4.0
    2.0  4.0  6.0   8.0
    3.0  6.0  9.0  12.0

## reduce

In [2]:
map(x -> x^2, 1:3)

3-element Vector{Int64}:
 1
 4
 9

In [4]:
reduce(+, 1:3)

6

In [5]:
# 先map然后再reduce
mapreduce(x->x^2, +, 1:3)

14

In [6]:
a = randn(2, 2)

2×2 Matrix{Float64}:
 0.0199479  0.841769
 2.50853    0.366755

In [7]:
permutedims(a, (2, 1))

2×2 Matrix{Float64}:
 0.0199479  2.50853
 0.841769   0.366755

## 视图

In [100]:
m1[1, 1] = 1

1

In [101]:
m1

3×4 Matrix{Float64}:
 1.0  2.0  3.0   4.0
 2.0  4.0  6.0   8.0
 3.0  6.0  9.0  12.0

In [103]:
m1[1, :] = [4, 3, 2, 1]

4-element Vector{Int64}:
 4
 3
 2
 1

In [105]:
m1

3×4 Matrix{Float64}:
 4.0  3.0  2.0   1.0
 2.0  4.0  6.0   8.0
 3.0  6.0  9.0  12.0

视图与正常的索引有什么区别？
+ 如果需要直接修改原来的数组好像也没啥区别，貌似view快一点
+ 如果是先取出数组的某一块然后赋值给一个新变量，这时view的数组上的修改会直接反应到原来的数组上，但是新变量的修改并不会反映到原来数组上，因为新变量是取出的数组块的复制。

> 当涉及到的矩阵比较大时用view,只涉及索引不涉及赋值用view

In [107]:
B = m1[2, :]

4-element Vector{Float64}:
 2.0
 4.0
 6.0
 8.0

In [108]:
B[1] = 100

100

In [109]:
m1

3×4 Matrix{Float64}:
 4.0  3.0  2.0   1.0
 2.0  4.0  6.0   8.0
 3.0  6.0  9.0  12.0

In [110]:
B

4-element Vector{Float64}:
 100.0
   4.0
   6.0
   8.0

In [111]:
C = @view m1[2, :]

4-element view(::Matrix{Float64}, 2, :) with eltype Float64:
 2.0
 4.0
 6.0
 8.0

In [112]:
C[1] = 100

100

In [113]:
m1

3×4 Matrix{Float64}:
   4.0  3.0  2.0   1.0
 100.0  4.0  6.0   8.0
   3.0  6.0  9.0  12.0

In [120]:
rmat = rand(10000, 10000);

In [140]:
using BenchmarkTools

In [144]:
@benchmark @view rmat[3:5000, 1299:2:3000]

BenchmarkTools.Trial: 10000 samples with 996 evaluations.
 Range (min … max):  24.900 ns …  39.857 μs  ┊ GC (min … max): 0.00% … 99.78%
 Time  (median):     57.329 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   59.626 ns ± 398.232 ns  ┊ GC (mean ± σ):  6.67% ±  1.00%

        ▂                   ▃▄▆█▆▄▁                             
  ▂▂▂▆▄▅█▄▃▃▂▂▂▂▁▂▂▃▂▂▂▂▂▃▅████████▇▆▅▄▄▃▃▃▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂ ▃
  24.9 ns         Histogram: frequency by time         91.6 ns <

 Memory estimate: 80 bytes, allocs estimate: 1.

In [145]:
@benchmark rmat[3:5000, 1299:2:3000]

BenchmarkTools.Trial: 437 samples with 1 evaluation.
 Range (min … max):   7.127 ms … 41.789 ms  ┊ GC (min … max):  0.00% … 75.43%
 Time  (median):      9.428 ms              ┊ GC (median):     0.00%
 Time  (mean ± σ):   11.429 ms ±  7.631 ms  ┊ GC (mean ± σ):  18.62% ± 19.84%

  ▂  ▄█▁                                                    ▁  
  █▇▅███▅▄▁▁▁▁▁▁▁▁▁▁▄▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▄▄▅▄▄▆█ ▆
  7.13 ms      Histogram: log(frequency) by time      39.5 ms <

 Memory estimate: 32.45 MiB, allocs estimate: 2.

## 矢量化计算

In [146]:
a = [1.2, 3.5, -2.1]

3-element Vector{Float64}:
  1.2
  3.5
 -2.1

In [147]:
map((x) -> x + 1, a)

3-element Vector{Float64}:
  2.2
  4.5
 -1.1

In [149]:
map(a) do element
    element + 1
end

3-element Vector{Float64}:
  2.2
  4.5
 -1.1

In [158]:
map(a) do element
        if element < 0
            return 0
        elseif element > 0 && element < 3
            return Int64(round(element))
        else
            return 1000
        end
end
        

3-element Vector{Int64}:
    1
 1000
    0

In [159]:
broadcast(+, (1, 2, 3), -1)

(0, 1, 2)

In [174]:
c = (2, 3, -5, 5)

(2, 3, -5, 5)

In [175]:
b = (0, 1, -1, -2)

(0, 1, -1, -2)

In [176]:
max.(c, b)

(2, 3, -1, 5)

In [181]:
max(c, b)

(2, 3, -5, 5)

In [180]:
@. max(c, b)

(2, 3, -1, 5)

In [179]:
@__dot__ max(c, b)

(2, 3, -1, 5)

## 排序

In [182]:
a = [2, 3, 1, 4]

4-element Vector{Int64}:
 2
 3
 1
 4

In [183]:
sort(a)

4-element Vector{Int64}:
 1
 2
 3
 4

In [185]:
sortperm(a) # 获得排序前个元素的下标值

4-element Vector{Int64}:
 3
 1
 2
 4

In [186]:
b = [1  2  3;
     4  1  2;
     0  3  7]

3×3 Matrix{Int64}:
 1  2  3
 4  1  2
 0  3  7

In [189]:
sort(b, dims = 1)

3×3 Matrix{Int64}:
 0  1  2
 1  2  3
 4  3  7

In [190]:
sort(b, dims = 2)

3×3 Matrix{Int64}:
 1  2  3
 1  2  4
 0  3  7

In [192]:
sort(b, dims = 2, rev = true)

3×3 Matrix{Int64}:
 3  2  1
 4  2  1
 7  3  0

## 查找

In [193]:
1 in [1, 2, 3]

true

In [194]:
in(1, [1, 2, 3])

true

In [198]:
findmax([3, -1, 1, 2, 4])

(4, 5)

In [199]:
a = [1  4  -1;
     3  2   0;
     2  5   1]

3×3 Matrix{Int64}:
 1  4  -1
 3  2   0
 2  5   1

In [204]:
findmax(a, dims =1)[2][1]

CartesianIndex(2, 1)

In [205]:
a[findmax(a, dims =1)[2][1]]

3

In [206]:
findall(iszero, a)

1-element Vector{CartesianIndex{2}}:
 CartesianIndex(2, 3)

In [207]:
findall(isone, a)

2-element Vector{CartesianIndex{2}}:
 CartesianIndex(1, 1)
 CartesianIndex(3, 3)

## 矩阵操作

In [208]:
using LinearAlgebra

In [209]:
A = rand(3, 3)

3×3 Matrix{Float64}:
 0.315813   0.499762  0.526874
 0.719178   0.920692  0.957881
 0.0162672  0.424161  0.721809

In [210]:
tr(A)

1.9583148936786183

In [211]:
det(A)

-0.01724893501880975

In [212]:
inv(A)

3×3 Matrix{Float64}:
 -14.973     7.95724   0.369638
  29.1918  -12.7188   -4.42951
 -16.8167    7.2947    3.98001

In [213]:
A'

3×3 adjoint(::Matrix{Float64}) with eltype Float64:
 0.315813  0.719178  0.0162672
 0.499762  0.920692  0.424161
 0.526874  0.957881  0.721809

In [214]:
eigvals(A)

3-element Vector{Float64}:
 -0.03589191276678614
  0.28041992470338933
  1.7137868817420145

In [215]:
eigvecs(A)

3×3 Matrix{Float64}:
 -0.466859  -0.281379  -0.431521
  0.775885  -0.686705  -0.826878
 -0.424317   0.670271  -0.360642

In [216]:
diag_mat = Diagonal([1, 2, 3])

3×3 Diagonal{Int64, Vector{Int64}}:
 1  ⋅  ⋅
 ⋅  2  ⋅
 ⋅  ⋅  3